config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'visitors#index'
  devise_for :users
  resources :events
  resources :shopping_cart, controller: 'shopping_carts'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :performances
end

app/models/performance.rb
# frozen_string_literal: true

class Performance < ApplicationRecord
  belongs_to :event
  has_many :tickets

  def unsold_tickets(count)
    tickets.where(status: 'unsold').limit(count)
  end
end

app/models/shopping_cart.rb
# frozen_string_literal: true

class ShoppingCart
  attr_accessor :user

  def initialize(user)
    @user = user
  end

  def tickets
    @tickets ||= user.tickets_in_cart
  end

  def events
    tickets.map(&:event).uniq.sort_by(&:name)
  end

  def tickets_by_performance
    tickets.group_by { |t| t.performance.id }
  end

  def performance_count
    tickets_by_performance.each_pair.each_with_object({}) do |pair, result|
      result[pair.first] = pair.last.size
    end
  end

  def performances_for(event)
    tickets.map(&:performance)
           .select { |performance| performance.event == event }
           .uniq.sort_by(&:start_time)
  end

  def subtotal_for(performance)
    tickets_by_performance[performance.id].sum(&:price)
  end

  def total_cost
    tickets.map(&:price).sum
  end
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :performance

  has_one :event, through: :performance

  monetize :price_cents

  enum status: { unsold: 0, waiting: 1 }
  enum access: { general: 0 }

  def place_in_cart_for(user)
    update(status: :waiting, user:)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :tickets

  def tickets_in_cart
    tickets.waiting.all.to_a
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/shopping_carts_controller.rb
# frozen_string_literal: true

class ShoppingCartsController < ApplicationController
  def show
    @cart = ShoppingCart.new(current_user)
  end

  def update
    performance = Performance.find(params[:performance_id])
    workflow = AddsToCart.new(
      user: current_user, performance:,
      count: params[:ticket_count]
    )
    workflow.run
    if workflow.success
      redirect_to shopping_cart_path
    else
      redirect_to performance.event
    end
  end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/shopping_carts_helper.rb
# frozen_string_literal: true

module ShoppingCartsHelper
end

app/helpers/visitors_helper.rb
# frozen_string_literal: true

module VisitorsHelper
end

app/views/events/index.html.slim
h2 Upcoming Performances

- @events.each do |event|
  h2= link_to(event.name, event_path(event))

app/views/events/show.html.slim
h1= @event.name

h2 Available Performances
- @event.performances.each do |performance|
  div(id=dom_id(performance))
    .row
      = form_tag(shopping_cart_path, method: :patch) do
        = hidden_field_tag("performance_id", performance.id)
        .col-md-2
          h4= performance.start_time
        .col-md-1
          .form-group
            = select_tag("ticket_count",
                options_for_select((1..10).to_a), class: "form-control")
        .col-md-3
          .form-group
            = submit_tag("Add to Cart",
                class: "btn btn-primary", id: "add-to-cart")

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert(class="alert-#{name.to_s == "notice" ? "success" : "danger"}")
      button.close(
        type="button" data-dismiss="alert" aria-hidden="true") &times;
      div(id="flash_#{name}")= msg

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
    = link_to("Snow Globe Theater", root_path, class: "navbar-brand")
    ul.nav.navbar-nav
     = render "layouts/navigation_links"

app/views/layouts/_navigation_links.html.slim
li= link_to("Events", events_path)
- if user_signed_in?
  li= link_to("Edit account", edit_user_registration_path)
  li= link_to("Sign out", destroy_user_session_path, method: "delete")
- else
  li= link_to("Sign in", new_user_session_path)
  li= link_to("Sign up", new_user_registration_path)

app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width" initial-scale="1.0")
    title= content_for?(:title) ? yield(:title) : "Snow Globe Theater"
    meta(name="description"
      content="#{content_for?(:description) ? yield(:description) : "Globe"}")
    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("application", "data-turbolinks-track" => true)
    = csrf_meta_tags
  
  body
    header
      = render "layouts/navigation"
    main(role="main")
      .container
        = render "layouts/messages"
        = yield

app/views/shopping_carts/show.html.slim
h1 Shopping Cart

- @cart.events.each do |event|
  h2= event.name
  div(id=dom_id(event))
    table.table
      thead
        th Date
        th Tickets
        th Total Price
      tbody
        - @cart.performances_for(event).each do |performance|
          tr(id=dom_id(performance))
            td= performance.start_time.to_date
            td.ticket_count= @cart.performance_count[performance.id]
            td.subtotal
              = humanized_money_with_symbol(@cart.subtotal_for(performance))
            
h3 Total #{humanized_money_with_symbol(@cart.total_cost)}

app/views/visitors/index.html.slim
h3 Welcome